auth-server: http://localhost:8080/server
server:
  port: 8002
security:
  oauth2:
    client:
      client-id: lu2
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key